services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - my-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root # You can change this, but the default works in many cases
      ME_CONFIG_MONGODB_ADMINPASSWORD: example # **IMPORTANT: Change this to a secure password!**
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin # Optional: For basic auth in Mongo-Express
      ME_CONFIG_BASICAUTH_PASSWORD: password # Optional: For basic auth in Mongo-Express.  Change this!
    depends_on:
      - mongo
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data_container: # Named volume for MongoDB data persistence
