services:
  # meilisearch:
  #   image: getmeili/meilisearch:v1.7
  #   container_name: meilisearch
  #   ports:
  #     - "7700:7700"
  #   environment:
  #     - MEILI_MASTER_KEY=yourStrongSecretKey
  #   volumes:
  #     - meili_data:/meili_data

  meilisearch-ui:
    image: meilisearch/meilisearch-dashboard
    container_name: meilisearch-ui
    ports:
      - "8080:8080"
    environment:
      - VITE_MEILISEARCH_HOST=http://meilisearch:7700
      - VITE_MEILISEARCH_API_KEY=yourStrongSecretKey
    depends_on:
      - meilisearch

volumes:
  meili_data: