networks:
  local_dbnetwork: 
    name: "local_databases"

services:
  db:
    # DEFAULT IMAGE
    # image: postgres:latest
    # if you would want to enable the POSGIS geo extensions use this image, else use the default
    image: cmihai/postgis
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      # - ./local_pgdata:/var/lib/postgresql/data
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - db
    volumes:
      # This will mount your file system folder to the container.
      - ./pgadmin-data:/var/lib/pgadmin
      - ./pgtemp:/var/tmp

volumes:
  pg-data:
  pgadmin-data: