version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "mysecurepassword"]
    environment:
      - REDIS_PASSWORD=mysecurepassword

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mysecurepassword
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local
